#!/bin/sh /etc/rc.common

USE_PROCD=1
START=95
STOP=10

PROG=/usr/bin/oxidns
CONFIG=/etc/oxidns/config.yaml
WORKDIR=/var/lib/oxidns

start_service() {
	mkdir -p "$WORKDIR"
	procd_open_instance
	procd_set_param command "$PROG" start -c "$CONFIG" -d "$WORKDIR"
	procd_set_param respawn 3600 5 5
	procd_set_param stdout 1
	procd_set_param stderr 1
	procd_close_instance
}

reload_service() {
	procd_send_signal oxidns
}
